const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const context = vm.createContext({});
vm.runInContext(fs.readFileSync("app/static/music-search.js", "utf8"), context);
const existing = { id: 7, title: "白日", artist: "King Gnu", energy: 1, valence: 2, tension: 3, density: 4, closure: 5, media_uri: null };
const result = { title: "King Gnu - 白日", artist: "", media_uri: "https://www.youtube.com/watch?v=ony539T074w" };
const draft = context.musicDraft(result, [existing], new Map());
assert.equal(draft.existing.id, 7);
assert.equal(draft.values.energy, 1);
assert.equal(draft.values.title, "白日");
assert.equal(draft.values.media_uri, result.media_uri);
assert.equal(existing.media_uri, null);
const live = context.musicDraft({ ...result, title: "King Gnu - 白日 (Live)" }, [existing], new Map(), 7);
assert.equal(live.values.closure, 5);
assert.equal(live.values.title, "白日");
assert.throws(() => context.musicDraft(result, [], new Map(), 7));
assert.throws(() => context.musicDraft(result, [existing, { ...existing, id: 8 }], new Map()));
const unknown = context.musicDraft({ ...result, title: "New song" }, [existing], new Map());
assert.equal(unknown.existing, null);
assert.equal(unknown.values.artist, "");
assert.equal(unknown.values.energy, undefined);
assert.equal(context.isYouTubeUrl(result.media_uri), true);
assert.equal(context.isYouTubeUrl("https://www.youtube.com.evil.test/watch?v=ony539T074w"), false);
assert.equal(context.isYouTubeUrl("javascript:alert(1)"), false);
console.log("Music search UI: existing ratings, selected target, unknown ratings, duplicates and URL checks passed.");
